name: gl_app
description: "Money Management"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  go_router: ^13.2.1
  flutter_image_slideshow: any
  dropdown_button2: ^2.3.8
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  image_cropper: ^5.0.1
  url_launcher: ^6.2.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  firebase_storage: ^11.6.11
  fluttertoast: ^8.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
