name: gl_app
description: "Money Management"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  go_router: ^14.1.1
  flutter_image_slideshow: ^0.1.6
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.1
  dotted_border: ^2.1.0
  image_cropper: ^6.0.0
  url_launcher: ^6.2.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  fluttertoast: ^8.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
